layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Android Development
    web_url: https://developer.android.com/
    image_url: https://cdn.auth0.com/blog/android-libraries/logo.png
  
  - name: Web Development
    web_url: https://freecodecamp.org
    image_url: http://pluspng.com/img-png/web-development-png-download-web-development-png-images-transparent-gallery-advertisement-446.png
  
  - name: Data Science
    web_url: https://en.wikipedia.org/wiki/Data_science
    image_url: https://topdatascience.com/images/LOGO_6.png

  - name: Artificial Intelligence
    web_url: https://www.techopedia.com/definition/190/artificial-intelligence-ai
    image_url: https://banner2.kisspng.com/20180205/uaq/kisspng-logo-artificial-intelligence-digital-brain-5a7819e9936072.1879198715178203936037.jpg
