layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Android
    web_url: https://developer.android.com/
    image_url: https://cdn.auth0.com/blog/android-libraries/logo.png
  
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: HTML5
    web_url: https://www.w3schools.com/html/html5_intro.asp
    image_url: https://www.w3.org/html/logo/downloads/HTML5_Logo_512.png

  - name: JavaScript
    web_url: https://www.javascript.com/
    image_url: https://cdn.auth0.com/blog/es6rundown/logo.png

  - name: Java 
    web_url: http://assets.stickpng.com/thumbs/58480979cef1014c0b5e4901.png
    image_url: https://www.java.com/download/

  - name: Python
    web_url: https://www.python.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/2000px-Python-logo-notext.svg.png

  - name: Data Science
    web_url: https://en.wikipedia.org/wiki/Data_science
    image_url: https://topdatascience.com/images/LOGO_6.png

  - name: ML
    web_url: https://en.wikipedia.org/wiki/Machine_learning
    image_url: https://upload.wikimedia.org/wikipedia/commons/d/d5/Hey_Machine_Learning_Logo.png

  - name: AI
    web_url: https://www.techopedia.com/definition/190/artificial-intelligence-ai
    image_url: https://banner2.kisspng.com/20180205/uaq/kisspng-logo-artificial-intelligence-digital-brain-5a7819e9936072.1879198715178203936037.jpg
